### ISSUE TITLE
Return error or boolean if empty

### ISSUE THREAD

**Issue by Kaexburli** [kaisermann/svelte-i18n#186]
Hello,

First of all thank you for this excellent module which works very well!

I would like to make a request for modification of the module in the event of non-existent translation

Let me explain!

In my personal code I test the existence of a translation in the following way to know if in the table of the selected language (auth.msg) I have a value (test)

````
Object.prototype.hasOwnProperty.call($_(`auth.msg`), test)
````

this code works very well, but I have a warning message:

> [svelte-i18n] Message with id "auth.msg" must be of type "string", found: "object". Gettin its value through the "$format" method is deprecated; use the "json" method instead.

if the test value does not exist the module returns `auth.msg.test` as the translation value!

Would it be possible to return a boolean (false) instead or is it a deliberate and very useful choice for the module to return the non-existent string?

cordially
Franck

**Comment by ZerdoX-x** [comment]
Would it be fine as workaround if there would be way to disable warning? I will open another issue. I would like to have way to ignore warnings in specific cases:

```
function checkIfTranslationExists(key) {
  return $_(key, { disableWarnings: true }) !== key;
}
```

**Comment by Kaexburli** [comment]
Perfect !!!

**Comment by Kaexburli** [comment]
Resolved!

**Comment by ZerdoX-x** [comment]
@Kaexburli it will still throw a warning tho :) My code is just a proposal for library author.

**Comment by ZerdoX-x** [comment]
#187

**Comment by ZerdoX-x** [comment]
@Kaexburli Hey! Take a look at https://github.com/kaisermann/svelte-i18n/pull/175
